### ISSUE TITLE
idea: Driver Registry

### ISSUE THREAD

**Issue by jamesmunns** [tosc-rs/mnemos#11]
So, as of right now, I have sort of an ambiguous structure around "registering" a driver, vs just spawning a driver task in the kernel.

The original role of "registering" was to act as a routing mechanism for userspace messages. This is why it rejects duplicate "kind" registrations.

IMO, this is sort of good, and sort of not.

I had an idea to essentially have two kinds of drivers:

* Ones that exist as tasks, but only exist in service of some other driver, e.g. they are not "discoverable", they are just a task that does stuff for other drivers that already have access to talking to them (kchannels, bbqueues, etc.)
* Ones that exist as a "discoverable" item, e.g. ones that can be queries by other drivers that are not tightly couple to eachother (e.g. "give me the serial port"), or can be queried/addressed from userspace.

I think the "standard library" will have a handful of official/discoverable driver services (like block devices, serial ports), that will generally be expected to exist. This will fulfill the interface for userspace standard library interfaces.

I also think there is room for "third party" drivers which come with their own userspace libraries, as well as a kernel service.

I think it might make sense to decouple the message types across the user/kernel comms layer, and have the service registrations work as some kind of UUID that defines the service. That way, in userspace, you can say "does the kernel have `1234ABC-...` service?" and know whether you can operate with that.

**Comment by hawkw** [comment]
Pretty sure #25 implemented this :)
