### ISSUE TITLE
`cargo melpo` doesn't compile when in repo root, due to multiple `tracing` versions

### ISSUE THREAD

**Issue by Aloso** [tosc-rs/mnemos#142]
After checking out the repo and running `cargo melpo`, I get hundreds of errors similar to this:

```
error[E0659]: `Instrument` is ambiguous
   --> source/kernel/src/services/forth_spawnulator.rs:156:5
    |
156 |     #[tracing::instrument(skip(kernel, vms))]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of multiple glob imports of a name in the same module
```

The issue seems to be that both `tracing@0.2.0` and `tracing@0.1.37` are included in the dependency graph.

When I run the command in the `./sources/melpomene` directory, it works.

**Comment by hawkw** [comment]
ugh, that's annoying. we should either try to fix that, or change the cargo alias into a `just` recipe that `cd`s into the correct directory...

**Comment by hawkw** [comment]
now that mnemos-alloc supports `liballoc`, we could just cut over to `tracing` 0.1.x everywhere...
