### ISSUE TITLE
some kind of CI

### ISSUE THREAD

**Issue by hawkw** [tosc-rs/mnemos#27]
Now that multiple people are contributing to the repo...we should really be running some kind of CI to make sure that the code compiles, at least...

**Comment by jamesmunns** [comment]
Yeah, this is a very good call. I'm going to be mostly "out of office" tomorrow, should try to get to this over the weekend.

I need to find something not using actions-rs (maybe mycelium?) to set up basic build + tests + lints.

**Comment by hawkw** [comment]
feel free to copy from https://github.com/hawkw/mycelium/blob/main/.github/workflows/ci.yml, but note that it's also doing a bunch of stuff that we don't currently need (running tests in QEMU, running different sets of Loom and Miri tests based on which crates changed, etc)
